title: "KimLog"
description: "Unreal Engine / Web Tools "
theme: minima
plugins:
  - jekyll-feed
collections:
  devlog:
    output: true
    permalink: /devlog/:path/
header_pages:
  - devlog.html
  - ue5.md
  - tools.md
  - about.md
