title: "KimLog"
description: "Unreal Engine / Web Tools "
theme: minima
plugins:
  - jekyll-feed
collections:
  devlog:
    output: true
    permalink: /devlog/:name/
header_pages:
  - devlog.md
  - ue5/ue5.md
  - tools/tools.md
  - about.md
