title: "KimLog"
description: "Unreal Engine / Web Tools "
theme: minima
plugins:
  - jekyll-feed
collections:
  devlog:
    output: true
    permalink: /devlog/:name/
  tools:
    output: true
    permalink: /tool/:name/
  ue5:
    output: true
    permalink: /ue5/:name/
header_pages:
  - devlog.md
  - ue5.md
  - tools.md
  - about.md
